=== asmachercheri/pdb2lmp/data/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "oneOf": [
    {"required": ["molecules"]},
    {"required": ["bonds"]},
    {"required": ["atoms", "h_values"]}
  ],
  "additionalProperties": false,
  "properties": {
    "version": {"type": "object"},
    "notes": {"type": "string"},
    "include": {
      "type": "array",
      "uniqueItems": true,
      "items": {"type": "string"}
    },
    "molecules": {
      "type": "object",
      "additionalProperties": {"$ref": "#/definitions/molecule"}
    },
    "bonds": {
      "type": "object",
      "properties": {
        "length": {"$ref": "#/definitions/bondset"},
        "angle": {"$ref": "#/definitions/bondset"},
        "dihedral": {"$ref": "#/definitions/bondset"},
        "improper": {"$ref": "#/definitions/bondset"}
      }
    },
    "atoms": {
      "type": "object",
      "additionalProperties": {"$ref": "#/definitions/libatom"}
    },
    "h_values": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": {
          "type": "number",
          "minimum": 0
        }
      }
    }
  },

  "definitions": {

    "molecule": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "comment": {"type": "string"},
        "templates": {
          "type": "array",
          "minLength": 0,
          "items": {"type": "string"}
        },
        "polymer_type": {
          "type": "array",
          "uniqueItems": true,
          "items": {"type": "string"}
        },
        "atoms": {
          "type": "array",
          "uniqueItems": true,
          "minLength": 1,
          "items": {"$ref": "#/definitions/atom"}
        },
        "lengths": {
          "type": "array",
          "uniqueItems": true,
          "items": {"$ref": "#/definitions/length"}
        },
        "angles": {
          "type": "array",
          "uniqueItems": true,
          "items": {"$ref": "#/definitions/angle"}
        },
        "dihedrals": {
          "type": "array",
          "uniqueItems": true,
          "items": {"$ref": "#/definitions/dihedral"}
        },
        "impropers": {
          "type": "array",
          "uniqueItems": true,
          "items": {"$ref": "#/definitions/dihedral"}
        }
      }
    },

    "atom": {
      "type": "object",
      "required": ["name", "type"],
      "additionalProperties": false,
      "properties": {
        "name": {"type": "string"},
        "type": {"type": "string"},
        "charge": {"type": "number"}
      }
    },

    "length": {
      "type": "object",
      "required": ["type", "atoms"],
      "additionalProperties": false,
      "properties": {
        "type": {"type": "string"},
        "atoms": {
          "type": "array",
          "minLength": 2,
          "maxLength": 2,
          "uniqueItems": true,
          "items": {"type": "string"}
        }
      }
    },

    "angle": {
      "type": "object",
      "required": ["type", "atoms"],
      "additionalProperties": false,
      "properties": {
        "type": {"type": "string"},
        "atoms": {
          "type": "array",
          "minLength": 3,
          "maxLength": 3,
          "uniqueItems": true,
          "items": {"type": "string"}
        }
      }
    },

    "dihedral": {
      "type": "object",
      "required": ["type", "atoms"],
      "additionalProperties": false,
      "properties": {
        "type": {"type": "string"},
        "atoms": {
          "type": "array",
          "minLength": 4,
          "maxLength": 4,
          "uniqueItems": true,
          "items": {"type": "string"}
        }
      }
    },

    "bondset": {
      "type": "object",
      "additionalProperties": {"type": "string"}
    },

    "libatom": {
      "type": "object",
      "required": ["mass", "charge", "sigma", "epsilon", "dipole", "diameter"],
      "properties": {
        "mass": {
          "type": "number",
          "minimum": 0
        },
        "charge": {
          "type": "number"
        },
        "sigma": {
          "type": "number",
          "minimum": 0
        },
        "epsilon": {
          "type": "number",
          "minimum": 0
        },
        "dipole": {
          "type": "number",
          "minimum": 0
        },
        "diameter": {
          "type": "number",
          "minimum": 0
        }
      }
    }
  }
}

=== asmachercheri/pdb2lmp/data/mol-elba-sugar.json
{
  "version":{
    "sugar": 1
  },
  "notes": "These parameters are temporary",
  "include":[
    "elba-sugar/glucose.json"
  ],
  "molecules":{
    "MEO":{
      "atoms":[
        {"name": "C",  "type": "MEOH"}
      ]
    },
    "ETO":{
      "atoms":[
        {"name": "C",  "type": "ETOH"}
      ]
    }
  }
}
